### ISSUE TITLE
关于SeqLoRA和IncLoRA

### ISSUE THREAD

**Issue by LiangJian24** [cmnfriend/O-LoRA#29]
感谢您的工作！想请问一些小问题。请问SeqLoRA和IncLoRA的区别，是否在于：SeqLoRA在每次训练完一个任务后不会把lora和模型参数合并；而IncLoRA会把lora和模型参数合并，并且使用一个新的lora训练新任务？

**Comment by cmnfriend** [comment]
都没有和完整的模型参数合并，seqlora是始终在原本的lora参数上训练，这个参数的形状不变，而inclora是使用一个新的lora训练新任务后和之前的lora参数合并

**Comment by LiangJian24** [comment]
感谢解答
