### ISSUE TITLE
random_seed设置以及原生lora问题

### ISSUE THREAD

**Issue by qwpyyx** [cmnfriend/O-LoRA#34]
您好，想请问一下原始论文设置的seed是多少呢？好像在sh里面没有看到有seed的设置。此外想请问一下，如果我令lambda_1=0，相当于没了正则项，那是直接退回了increment LoRA吗？此外想请教一下SeqLoRA是不是就是原生的lora？有现成的命令吗？谢谢解惑
![image](https://github.com/user-attachments/assets/07cc1d96-f1d6-42cd-b555-ad1adeafb763)

**Comment by cmnfriend** [comment]
1. seed是默认值42，是transformers的TrainingArguments类的参数，可以自己改
2. 是的lambda=0就是incremental lora，原生lora是seqlora，没写直接跑的指令，需要改改代码

**Comment by qwpyyx** [comment]
好的，感谢！
